### list of the training classes
GET http://localhost:8080/api/trainingclasses
Accept: application/json


### create a new training class
POST http://localhost:8080/api/trainingclasses
Content-Type: application/json
Accept: application/json

{
  "title": "Junior Vállalati Java Backend",
  "beginEndDates": {
    "begin": "2021-06-01",
    "end": "2021-08-22"
  }
}


### update a training class
PUT http://localhost:8080/api/trainingclasses/1
Content-Type: application/json
Accept: application/json

{
  "title": "Junio Java Backend modified",
  "beginEndDates": {
    "begin": "2021-06-20",
    "end": "2021-08-06"
  }
}


### delete a training class
DELETE http://localhost:8080/api/trainingclasses/1
Content-Type: application/json
Accept: application/json
